version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  backend:
    build:
      context: ./devops-fullstack-app/backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5432
      ALLOWED_ORIGINS: http://localhost:3000
    networks:
      - mynetwork
    depends_on:
      - postgres

  frontend:
    build:
      context: ./devops-fullstack-app/frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
